version: "3"

services:
  cpuminer:
    container_name: cpuminer
    image: $IMAGE
    environment:
      - ALGO=$ALGO
      - URL=$URL
      - EMAIL=$EMAIL
      - PASSWORD=$PASSWORD
      - THREADS=$THREADS
    restart: unless-stopped