version: "3.8"

services:
  #-----------------------------------------------------------------------------
  # Foundry VTT
  # Virtual Table Top for gaming.
  foundry:
    image: felddy/foundryvtt:release

    volumes:
      - data:/data

    environment:
      FOUNDRY_USERNAME: $FOUNDRY_USERNAME
      FOUNDRY_PASSWORD: $FOUNDRY_PASSWORD
      FOUNDRY_ADMIN_KEY: $FOUNDRY_ADMIN_KEY

    networks:
      - net
      - shared_net

    deploy:
      labels:
        # Prometheus job label for querying via Prometheus.
        prometheus-job: foundry|foundry

    logging:
      options:
        # Log tagging for querying via Loki.
        tag: "foundry|foundry"

volumes:
  data:
    driver: local

networks:
  net:
    driver: overlay
  shared_net:
    external: true
