version: "3"
services:
  doge:
    container_name: doge
    image: $IMAGE
    ports:
      - "22555:22555"
      - "22556:22556"
      - "44555:44555"
      - "44556:44556"
    volumes:
      - data:/root/.dogecoin
    restart: unless-stopped

volumes:
  data:
    driver: local
