version: "3"
services:
  ltc:
    container_name: ltc
    image: $IMAGE
    ports:
      - "9332:9332"
      - "9333:9333"
      - "19332:19332"
      - "19333:19333"
    volumes:
      - data:/root/.litecoin
    restart: unless-stopped

volumes:
  data:
    driver: local
