FROM ubuntu:18.04

ENV LITECOIN_VERSION=0.18.1

# Install dependencies.
RUN \
  apt-get update -y \
  && apt-get install -y \
    libzmq3-dev=4.2.* \
  && rm -rf /var/lib/apt/lists/*

# Download binaries.
ADD https://download.litecoin.org/litecoin-${LITECOIN_VERSION}/linux/litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz /tmp
RUN \
  cd /opt \
  && tar zxvf /tmp/litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz \
  && mv litecoin-${LITECOIN_VERSION} litecoin

# Set execution command.
WORKDIR /opt/litecoin/bin
CMD ["/opt/litecoin/bin/litecoind"]

# Expose ports.
EXPOSE 9332 9333 19332 19333