version: "3.8"

services:
  #-----------------------------------------------------------------------------
  # BookStack
  # Wiki-like documentation tool.
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest

    volumes:
      - config:/config

    environment:
      PUID: "1000"
      PGID: "1000"
      APP_URL: $APP_URL
      DB_HOST: bookstack_database
      DB_PORT: "3306"
      DB_USER: bookstack
      DB_PASS: yourdbpass
      DB_DATABASE: bookstackapp

    networks:
      - net
      - shared_net

    depends_on:
      - database

    deploy:
      labels:
        # Prometheus job label for querying via Prometheus.
        prometheus-job: bookstack|bookstack

    logging:
      options:
        # Log tagging for querying via Loki.
        tag: "bookstack|bookstack"

  #-----------------------------------------------------------------------------
  # MariaDB
  # Database for BookStack.
  database:
    image: lscr.io/linuxserver/mariadb

    environment:
      PUID: "1000"
      PGID: "1000"
      MYSQL_ROOT_PASSWORD: yourdbpass
      TZ: $TIME_ZONE
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: yourdbpass

    volumes:
      - data:/config

    networks:
      - net

    deploy:
      labels:
        # Prometheus job label for querying via Prometheus.
        prometheus-job: bookstack|mariadb

    logging:
      options:
        # Log tagging for querying via Loki.
        tag: "bookstack|mariadb"

volumes:
  config:
    driver: local
  data:
    driver: local

networks:
  net:
    driver: overlay
  shared_net:
    external: true
