version: "3"

services:
  #----------
  # geth node
  geth:
    container_name: geth-rinkeby
    hostname: $ETH_HOST
    image: ethereum/client-go:stable
    command: --rinkeby --http --http.addr 0.0.0.0 --http.port $ETH_HTTP_PORT --http.corsdomain="*" --ws --ws.addr 0.0.0.0 --ws.port $ETH_WS_PORT --ws.origins="*" --datadir /geth

    volumes:
      - eth:/geth

    restart: unless-stopped

  #------------------
  # postgres database
  postgres:
    container_name: postgres-rinkeby
    hostname: $DB_HOST
    image: postgres

    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE

    volumes:
      - postgres:/var/lib/postgresql/data

    restart: unless-stopped

  #---------------
  # chainlink node
  chainlink:
    container_name: chainlink-rinkeby
    image: smartcontract/chainlink:1.1.0
    command: local n -p /chainlink/.password -a /chainlink/.api

    environment:
      ROOT: /chainlink
      LOG_LEVEL: debug
      ETH_CHAIN_ID: 4
      CHAINLINK_TLS_PORT: 0
      SECURE_COOKIES: "false"
      ALLOW_ORIGINS: "*"
      ETH_URL: ws://$ETH_HOST:$ETH_PORT
      DATABASE_URL: postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:5432/$DB_DATABASE?sslmode=disable

    volumes:
      - chainlink:/chainlink

    ports:
      - 6688:6688

    depends_on:
      - "geth"
      - "postgres"

    restart: unless-stopped

volumes:
  eth:
    driver: local
  chainlink:
    driver: local
  postgres:
    driver: local
