version: "3.9"

services:
  #-----------------------------------------------------------------------------
  # PiHole
  # DNS-based ad-blocker.
  pihole:
    image: pihole/pihole:latest

    volumes:
      - data:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d

    environment:
      TZ: $TIME_ZONE
      WEBPASSWORD: $WEB_PASSWORD
      VIRTUAL_HOST: $VIRTUAL_HOST
      FTLCONF_REPLY_ADDR4: $FTL_REPLY_ADDR4

    networks:
      - net
      - shared_net

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    cap_add:
      - NET_ADMIN

    deploy:
      labels:
        # Prometheus job label for querying via Prometheus.
        prometheus-job: pihole|pihole

    logging:
      options:
        # Log tagging for querying via Loki.
        tag: "pihole|pihole"

volumes:
  data:
    driver: local
  dnsmasq:
    driver: local

networks:
  net:
    driver: overlay
  shared_net:
    external: true
