version: "3"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: $TIME_ZONE
      WEBPASSWORD: $WEB_PASSWORD
      VIRTUAL_HOST: pihole
      FTLCONF_REPLY_ADDR4: $FTL_REPLY_ADDR4
    volumes:
      - data:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  data:
    driver: local
  dnsmasq:
    driver: local
