version: "3.8"

services:
  #----------------
  # Docker Registry
  registry:
    image: registry:latest

    volumes:
      - registry_data:/var/lib/registry

    networks:
      - net

    ports:
      - "5000:5000"

    deploy:
      labels:
        # Prometheus job label for querying via Prometheus.
        prometheus-job: docker|registry

    logging:
      options:
        # Log tagging for querying via Loki.
        tag: "docker|registry"

volumes:
  registry_data:
    driver: local

networks:
  net:
    driver: overlay
