version: "3"
services:
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - data:/var/opt/thelounge

volumes:
  data:
    driver: local