version: "3"

services:
  registry:
    image: registry:latest
    container_name: docker_registry
    ports:
      - 5000:5000
    volumes:
      - data:/var/lib/registry

    restart: unless-stopped

volumes:
  data:
    driver: local
