version: "3.8"

services:
  #-----------------------------------------------------------------------------
  # Portainer Server
  # Hosts the Portainer UI.
  portainer:
    image: portainer/portainer-ce:latest

    # You'll need to expose the port directly until you get NGINX deployed. Once
    # NGINX is live, you should come back and comment this out.
    #ports:
    #  - "9000:9000"

    volumes:
      - data:/data

    networks:
      - net
      - shared_net

    deploy:
      labels:
        # Prometheus job label for querying via Prometheus.
        prometheus-job: portainer|portainer

    logging:
      options:
        # Log tagging for querying via Loki.
        tag: "portainer|portainer"

  #-----------------------------------------------------------------------------
  # Portainer Agent
  # Makes Docker information from each swarm node available to the Portainer
  # server.
  portainer_agent:
    image: portainer/agent:latest

    volumes:
      # Grant access to the docker engine.
      - /var/run/docker.sock:/var/run/docker.sock
      # Grant access to docker volumes folder.
      - /var/lib/docker/volumes:/var/lib/docker/volumes

    networks:
      - net

    deploy:
      # This container needs to be running on each node.
      mode: global
      labels:
        # Prometheus job label for querying via Prometheus.
        prometheus-job: portainer|portainer-agent

    logging:
      options:
        # Log tagging for querying via Loki.
        tag: "portainer|portainer-agent"

# If you are using a cluster with more than one node, you'll need to implement
# a solution for distributed storage.
volumes:
  data:
    driver: local

networks:
  net:
    driver: overlay
  # Placing a container on the shared network lets NGINX reverse proxy traffic
  # to it.
  shared_net:
    external: true